package com.geometry;

public enum RelationType {
	GEO_RELATION, FACTOR_GEO_RELATION, EXPRESSION_RELATION, ADJACENT_ANGLES_ON_A_LINE_RELATION, 
	EXTERIOR_INTERIOR_ANGLE_RELATION, SUM_OF_ANGLES_IN_A_TRIANGLE_RELATION, RATIO_GEO_RELATION, PYTHAGORAS,TRIANGLESUM,VALUE_GEO_RELATION
}
